clone:
  git:
    image: bash
    settings:
      lfs: false

labels:
  backend: local

steps:
  - name: build-landing
    image: bash
    commands:
      - export PATH="/home/diama/.nvm/versions/node/v24.16.0/bin:$PATH"
      - cd landing-page
      - npm install
      - npm run build

  - name: deploy-landing
    image: bash
    commands:
      - export PATH="/home/diama/.nvm/versions/node/v24.16.0/bin:$PATH"
      - mkdir -p /home/diama/repos/project-aeris/landing-page/dist
      - cp -r landing-page/dist/* /home/diama/repos/project-aeris/landing-page/dist/
      - echo "Production static assets synced to live server path successfully!"

when:
  event: push
  branch: main